### ISSUE TITLE
travis-ciの設定

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#1]
公開された後、できるだけはやく @xuwei-k がやる予定。
公開前に準備できる部分は準備済。
自動でtravis-ciからgh-pages branchへpublishまでする予定

http://d.hatena.ne.jp/xuwei/20151126/1448537637

**Comment by xuwei-k** [comment]
masterにpushした。以下のあたりのコミットで完了したはず。travis確認したら閉じる

- https://github.com/dwango/scala_text/commit/938463d270132e5057f6fdb0d2
- https://github.com/dwango/scala_text/commit/3ba62552f73fade2
- https://github.com/dwango/scala_text/commit/27b5cba91b95b0afc5c05d

**Comment by pocketberserker** [comment]
badgeどうします？

**Comment by xuwei-k** [comment]
できた https://github.com/dwango/scala_text/commit/131ffa43bb1dc1

**Comment by xuwei-k** [comment]
badgeもつけました 
https://github.com/dwango/scala_text/commit/99dbd63dae87
