### ISSUE TITLE
Monoidの説明で、結合則が抜けているような…？

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#101]
> ```scala
> def leftIdentity[F](a: F)(implicit F: Monoid[F]): Boolean = a == F.append(F.zero, a)
> def rightIdentity[F](a: F)(implicit F: Monoid[F]): Boolean = a == F.append(a, F.zero)
> ```

これに加えて、

```scala
def associativeLaw[F](a: F, b: F, c: F)(implicit F: Monoid[F]): Boolean = {
  F.append(F.append(a, b), c) == F.append(a, F.append(b, c))
}
```

が必要なのではないかと。

**Comment by pocketberserker** [comment]
あっ、おっしゃる通りassosiative入れ忘れてますね…
