### ISSUE TITLE
型クラスの章に★表記がない

### ISSUE THREAD

**Issue by matsu-chara** [dwango/scala_text#107]
以下の表記で優先度を付けたほうが良さそうです。

```
本テキストでは、節や項ごとに、どの程度重要かを示すために★マークを付けていることがあります。以下に基準を示しますので、参考にしてください。

★★★： 必ず読むべき（must）
★★：読んだ方がいい（should）
★：読むといいかも（may）
```

https://github.com/dwango/scala_text/blob/master/src/typeclass.md

**Comment by xuwei-k** [comment]
2つか1つですかね？

**Comment by y-yu** [comment]
記事から★と★★の節をいくつか抜粋してきました。

### ★

- 「構文」と「式」と「文」という用語について
- 「トレイト」という用語について
-  線形化（linearization）
- abstract override

### ★★

- while式
- 菱形継承問題
- 自分型
- 変位指定（variance）

個人的には★★かなと思います。
