### ISSUE TITLE
"コードカバレッジを図る" の "はかる" で "図" という漢字は適切ではない？

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#111]
誰か日本語詳しい人・・・。面倒なら "ひらがな" にするか、"計測する"　みたいに別の言葉で言い換えるか

- https://github.com/dwango/scala_text/blob/b226cd87ea786771070231390c0b4ec8a52a822f/src/test.md#コードカバレッジの測定
- http://woman.mynavi.jp/article/130930-019/
- http://oshiete.goo.ne.jp/qa/773330.html

**Comment by kmizu** [comment]
測る、でいいのでは。
