### ISSUE TITLE
Promiseの説明文

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#113]
https://github.com/dwango/scala_text/blob/fa2d8bbe328aa684287ae13717eddaa92f2ba409/src/future-and-promise.md

> Promiseは一度だけ成功と定義した値または値と定義した処理を与えることでFutureに変換できる型

というの、なんかわかりずらいと感じるのは自分だけでしょうか？(いや、自分だけだったらcloseしていいです)

少なくとも、どこかに 読点 `、` があったほうがいいような・・・？
もしくはみんなわかりずらいと感じるなら、その文書き直してもいいけれど

**Comment by kmizu** [comment]
確かにわかりづらいですね…
