### ISSUE TITLE
sbtのlauncherのversion確認方法が、sbtのversionにより異なる

### ISSUE THREAD

**Issue by jyane** [dwango/scala_text#122]
sbtのversion確認方法は状況により異なり、`sbt --version`　では動作しない場合がある。
[https://github.com/dwango/scala_text/blob/master/src/sbt-install.md](https://github.com/dwango/scala_text/blob/master/src/sbt-install.md)

- 0.13.8では動作して、0.13.9以降だと動作しない(?)

**Comment by xuwei-k** [comment]
(微妙に追記、修正した)

**Comment by xuwei-k** [comment]
わかった

- sbt 0.13.8 以前で `--version` の処理してる部分はここ https://github.com/sbt/sbt/blob/v0.13.8/launch/src/main/scala/xsbt/boot/Boot.scala
- sbt 0.13.9 以降だと、launcher のリポジトリ分かれてる
- 0.13.9以降、launcherとsbt本体のversionは合わせなくなった
- よって、0.13.9以降 launcher 自体の version を表示するためには以下の部分で処理してるように `--launcher-version` という引数を渡すと "launcher自体のversion" を表示させることが可能 https://github.com/sbt/launcher/blob/v1.0.0-M1/launcher-implementation/src/main/scala/xsbt/boot/Boot.scala#L23


で、この詳細を別にscalatext本体に書く必要もそれほどないが、どうしようかな・・・

**Comment by matsu-chara** [comment]
sbt-install.mdは入門時期によむはずなので、 `sbt sbt-version` でバージョンを表示してもらうのが良さそうかなと思いました。（注釈で `sbt --launcher-version` についても言及するのがベストでしょうか）

**Comment by xuwei-k** [comment]
もともと書いた意図としては

- sbt 0.12 の launcher がインストールされてる場合に、それを使って `project/build.properties` に `sbt.version=0.13.11` などと書いても、起動に失敗する
- その起動に失敗する原因の特定のためにsbt自体ではなく「sbtのlauncherのverison」の表示方法を書きたかった
- つまり、sbt自体のversionを表示したかったわけではない。sbtのversionが表示できている時点で、sbtの起動には成功しており、上記のような問題はすでに発生の心配がない状態なはず

ので、個人的には

- あくまでlauncherのversionの表示方法をこだわって書く
- 「とくかく最新版のlauncherをちゃんとインストールしろ」みたいにあえて雑に変えてお茶を濁す

のどちらかな気がしている・・・？
(つまり `sbt sbt-version でバージョンを表示してもらうのが良さそう`  という意見には反対である)


`sbt sbt-version` のversion表示は、  `project/build.properties` とおなじになるはず？なので、通常それで見る意味があまりないというか

**Comment by matsu-chara** [comment]
なるほど `sbt 0.12 の launcher がインストールされてる場合に、それを使って project/build.properties に sbt.version=0.13.11 などと書いても、起動に失敗する` について把握してませんでした。たしかにそうなるとsbt自体のバージョンを表示しても余り意味が無さそうですね・・。
となると `sbt --launcher-version` で確認してください。 という指示が良さそうでしょうか。（sbt自体のバージョンは `sbt sbt-version` か `project/build.properties` を確認してくださいみたいな注釈付きで）

**Comment by xuwei-k** [comment]
あまり必要ない歴史的なトリビア

昔はlauncher毎回更新必要だったが0.12以降そんなことなくなった http://d.hatena.ne.jp/xuwei/20120528/1338168090

↓

0.12のlauncherで0.13も起動できるようにする予定だったが、意図せず互換崩れた https://github.com/sbt/sbt/commit/001bd6cb9f203c42e95
