### ISSUE TITLE
6.Scalaの制御構文のwhile式の練習問題の関数名が異なる

### ISSUE THREAD

**Issue by Thiry1** [dwango/scala_text#123]
https://github.com/dwango/scala_text/blob/master/src/control-syntax.md#%E7%B7%B4%E7%BF%92%E5%95%8F%E9%A1%8C-control_syntax_ex2

- 「`loopFrom0To9` は次のような形になります」とあるが、定義されている関数名は`loop0To9`となっている。

**Comment by kmizu** [comment]
Thanks!
