### ISSUE TITLE
6.Scalaの制御構文のwhile式の練習問題の説明と解答例が異なる

### ISSUE THREAD

**Issue by Thiry1** [dwango/scala_text#125]
https://github.com/dwango/scala_text/blob/master/src/control-syntax.md#%E7%B7%B4%E7%BF%92%E5%95%8F%E9%A1%8C-control_syntax_ex2
「`???`の部分を埋めてください。」とあるが、解答例は`???`以外の部分に` var i = 0`と書いている。

**Comment by kmizu** [comment]
確かにそうですね。
