### ISSUE TITLE
4. sbtでプログラムをコンパイル・実行するで sbt の起動方法を勘違いしやすい

### ISSUE THREAD

**Issue by hiroshi-cl** [dwango/scala_text#126]
> さて、このようにファイルを配置したらsandboxディレクトリに入り、sbtを起動します。するとsbtのプロンプトが出て、sbtのコマンドが入力できるようになります。

というところで、ここまで `sbt console` しか出てこなかったので、 盲目的に `sbt console` を使うものだと誤解してしまう例が見られました。起動方法に関する注釈が必要そうです。

**Comment by y-yu** [comment]
#129 で修正されたので、クローズします。
