### ISSUE TITLE
6. 制御構文、について Scala の while には break, continue がない

### ISSUE THREAD

**Issue by hiroshi-cl** [dwango/scala_text#127]
> Javaのものとほぼ同じです。

Java と違って break, continue がない、あるいは `scala.util.control.Breaks`  を使うというのは補足しておいた方がいいかもしれません。

**Comment by xuwei-k** [comment]
`scala.util.control.Breaks` はあまり使わないし、(優先度的に)書かなくてもいいんじゃないかなぁ、とは個人的に思うけど。

まぁ書いてダメなわけでもないから、書いてもいいけど、書いてないことをissueに上げていくとなんかキリがない、みたいな気持ちはある。それもまぁちゃんとgithubのissueのlabel付けして、issueが整理されていれば問題無いとも言えるけど。


Javaとかのbreakなどがある言語の経験がある人だと、わりと疑問に思うところなのだろうか？

**Comment by kmizu** [comment]
まあ、whileがあるC系言語のほとんどはbreak, continueあるので、Scalaにはそれがないという事くらいは言ってもいいかもしれないです。`Breaks`は例外を使っているせいで非直観的な挙動をすることがあり、あまり勧められないですね…。

**Comment by hiroshi-cl** [comment]
Java の (for/)while だと break, continue がセットなので、構文がほぼ同じと書いて Java の発想を流用できるかのようにいうのは問題ありませんかね？という意味で書きました。(厳密に言うと break, conitnue は (for/)while の構文の一部ではないので間違ってはいませんが)
Breaks については私も使うべきではないと思っていますが、一応言及しました。

**Comment by xuwei-k** [comment]
まぁ自らすすんで書く気はあまり起きないけど、別に入れること自体に反対でもないので、pull reqください、でいいかな
