### ISSUE TITLE
travis-ci上でcalibreのダウンロードのログが数千行も占領していて辛い

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#14]
現時点で思いつく選択肢を列挙

- calibreダウンロードやめる = travisでepub生成やめる?
- 毎回ダウンロードせず、どこかにキャッシュしておく？
- 何らかのオプション指定などの工夫により、毎回ダウンロードはするが、ログが大量に表示されないように工夫する？
- そこまで大きな問題ではないので、諦める？
- その他？

**Comment by pocketberserker** [comment]
必要な人はローカルでインストールすれば手に入るわけですし、生成を止めても特に問題ないのではないでしょうか。

**Comment by xuwei-k** [comment]
そうですねー。毎回生成はしなくてもいいかなぁ。
ただ、epubが簡単に見れるようになっているのは、それはそれで便利だと思うので、なんらかの方法である程度定期的にepub生成して、(このリポジトリのgh-pages以外でもいいけれど)どこかに置きたい気はする。

**Comment by pocketberserker** [comment]
もしくは、少し煩雑になりますが`master`でのみ生成するのはどうでしょう？
（pull requestのログは見る頻度高いですが、`master`は基本的にビルドに成功したものが取り込まれるはずなのでそんなにログをみないだろう、という推測）

**Comment by xuwei-k** [comment]
> masterでのみ生成

なるほど？pull reqでの変更により「html生成には成功するが、epub生成には失敗する」というパターンが、どれくらいありえるのか？によるかなぁ
(どのくらいありえるのか、あまり想像ついてない)

**Comment by xuwei-k** [comment]
個人的にログが見づらいのと、テストはじまる前に時間かかるのが微妙だと思ってる面もあるので、tutやtestやhtml生成全部実行して、それらが成功した後になって初めてcalibreをダウンロードしてepub生成、というように、やること同じでも順番変える、という方法もあるかもしれない

**Comment by pocketberserker** [comment]
おーなるほど、順番変えるでも良さそうですね。

**Comment by xuwei-k** [comment]
https://github.com/dwango/scala_text/pull/18 で順番は変えたけど、もう少しまだ改善方法あればやりたい気もするので、まだcloseせずに残しておくかなぁ
