### ISSUE TITLE
難易度表記の有無が一貫していない

### ISSUE THREAD

**Issue by matsu-chara** [dwango/scala_text#143]
★が全くない章もあるのである程度統一が必要そうだと思いました。　

https://y-yu.github.io/scala_text_pdf/scala_text.pdf#page=3

選択肢

1. 章ごと
2. 章・節ごと
3. 全部とってしまう
4. 統一しなくてよい
5. `abstract override` など、補足的な節であるという目印を除いて、難易度表記自体を削除してしまう。(追記)

**Comment by matsu-chara** [comment]
選択肢1, 2の場合は `#`, `##` から始まる見出し行に★が含まれることを検出するtextlintプラグインを作れそうです。

**Comment by y-yu** [comment]
僕は節（`##`）ごとにあるのが適当かなと思います。そして、★をチェックするtextlintプラグインは今後の加筆などを考えると、もし★の運用を続け、かつ簡単に作れそうならあってよいと思います。

**Comment by matsu-chara** [comment]
節より深い部分で★をつけるかどうか、みたいな部分の統一も必要そうな気がしてきました。

```
### [Range](https://github.com/scala/scala/blob/v2.11.8/src/library/scala/collection/immutable/Range.scala)（★★）
...
### mkString：文字列のフォーマッティング（★★★）
#### mkString
```

https://github.com/matsu-chara/textlint-rule-chapter-difficulty-stars
`#, ##` は★あり（強制）
`###~` は★なし（強制）
の場合は69箇所の修正が必要です。（★つけるだけなのでそんなに大変ではなさそうです）

textlint結果： https://gist.github.com/matsu-chara/c9c5dd9c9cc089492ac8288785990538

**Comment by kmizu** [comment]
難易度表記はあえてつけるなら、練習問題につけるべきという話になったと思うので、これはいったんcloseします
