### ISSUE TITLE
Treeの問題の解答例のfindやfindBinaryTreeというメソッドに対応する問題がない？

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#146]
https://github.com/dwango/scala_text/blob/0df65e6befb6fde1e770d8f145f4b37113ccabc5/src/case-class-and-pattern-matching.md
- 今から対応する問題を追加する(整理や移動してて、どこかの時点で問題が抜け落ちた？最初からなかった？)
- findやfindBinaryTreeを単に消す
- その他？

**Comment by kmizu** [comment]
去年の研修の時点では必要だから作ったはずだったのですが、その後、テキストを改修する際に、`find`や`findBinaryTree`を作る問題の記述が抜け落ちた可能性が高いです。後で問題追加したいです。
