### ISSUE TITLE
Introductionのplay frameworkに関する記述の修正または削除？

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#15]
> Play 2 Scala Webアプリケーションフレームワークを用いたWebアプリケーションを開発できるようになること

や、また

> Playフレームワークは、Scalaの言語開発者たちが設立したTypesafe社でメンテナンスされていることもあり、Scalaの中では最も人気のあるWebフレームワークになっています。ドワンゴでも広く採用されており、新卒のみなさんが目にする機会も多くなるでしょう。

といった記述があるが、今回公開した部分にplay frameworkの具体的な使い方の記述などはないため、変なことになっている？

- 削除か修正が必要？
- 「Scalaの基本が身につく => Playで開発できるようになる(という準備ができる)」という意味では残しておいてよい？

**Comment by pocketberserker** [comment]
残すにしても、少し表現を変えたほうが良いと思います。

**Comment by kmizu** [comment]
修正文面案でいいのが思いつかなかったので、とりあえず削除しましょう。

**Comment by xuwei-k** [comment]
https://github.com/dwango/scala_text/pull/19 で削除したのでclose
