### ISSUE TITLE
型クラスの紹介　メソッド表記の揺れ

### ISSUE THREAD

**Issue by hmiyado** [dwango/scala_text#158]
Monadの規則の紹介ではleftIdentityLawとrightIdentityLawとLawがついているのに対して、Monoidの規則の紹介ではleftIdentityとrightIdentityになっており、Lawがついていない

https://github.com/dwango/scala_text/blob/master/src/typeclass.md

**Comment by pocketberserker** [comment]
#163 で修正されたのでclose
