### ISSUE TITLE
多相性に関する記述を追加する

### ISSUE THREAD

**Issue by y-yu** [dwango/scala_text#160]
型クラスの章などに、次の文書で説明されているような3つの多相性について述べて、型クラスのモチベーションについて説明するような文章を追加したい。

http://www.fos.kuis.kyoto-u.ac.jp/~igarashi/class/sf07w/resume6.pdf

また、「サブタイプ多相 vs アドホック多相」や「オーバーロード vs 型クラス」など進んだ話題に言及してもよいかもしれない。

**Comment by kmizu** [comment]
多相性に関する記述を追加すると、難易度が上がり過ぎると思うので、いったんクローズします
