### ISSUE TITLE
データ構造の実装に関する章を追加する

### ISSUE THREAD

**Issue by y-yu** [dwango/scala_text#161]
コレクションの章では、ListやMap、Vectorといったデータ構造が紹介されているが、性能の議論をするうえではこれらのデータ構造がどのような実装になっているのか、ということはおさえておいた方がよいと思われる。
そこで、Vectorなどのデータ構造がどのように実装できるのかという話題を、ケースクラスの章の後などに追加するのがよいと思う。

**Comment by kmizu** [comment]
`List`とかはいいのですが、`Map`(TreeMapなど）、`Vector`は結構複雑なので、このテキストで解説するのはちょっと難しいような。概要だけでいいのなら、

http://docs.scala-lang.org/ja/overviews/collections/introduction

見てもらう方が良いと思います。
