### ISSUE TITLE
トレイトの自分型の説明にある実行例が間違っている

### ISSUE THREAD

**Issue by zukky162** [dwango/scala_text#170]
Robot1とRobot2を使う例で、`r: Robot2`に値を代入しているにもかかわらず、次の行が`r: Robot = $anon$1@10470bfa`となっています。
https://github.com/dwango/scala_text/blob/master/src/trait.md

**Comment by xuwei-k** [comment]
手動チェック面倒だから、やっぱり多少書き方変えても、できる限りtut使うようにするか・・・
