### ISSUE TITLE
GitBook 3.0にバージョンアップする？

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#172]
今のところregexplaceとかが動かないという話をどこかで聞いた気がしますが、忘れないように一応Issueに登録しておく

**Comment by matsu-chara** [comment]
参考 https://github.com/matsu-chara/scala_text/commit/7d6ce0e65c03f770e89f88296eb22e322a95f46c

**Comment by matsu-chara** [comment]
https://github.com/markomanninen/gitbook-plugin-regexplace/commit/5e4d802f10cea94a37b6074b65dfdd656e13bb66

プラグインが対応した波動を感じるので、隙を見て更新しようかなとおもいますー
