### ISSUE TITLE
covariance/contravariacneの「どこがうれしいか」を明確にする

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#180]
- 現在は、機能の説明はあるが、どういうときにうれしいかの説明がほとんどない
- Java Wildcard(use-site variance)との対比があるとよいかも

**Comment by matsu-chara** [comment]
https://gist.github.com/matsu-chara/b412861a01cf333311c6aa48a7e20e50 をベースに足してみる？という話し

**Comment by kmizu** [comment]
加筆予定がないので、いったん閉じる
