### ISSUE TITLE
SetやMapと併置してListが紹介されているのは不自然

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#189]
scala_text勉強会での指摘

SetやMapは具体的なデータ構造を規定しないのに対して、Listは具体的なデータ構造なので併置されているのに違和感がある

**Comment by xuwei-k** [comment]
scala_text勉強会とは

**Comment by kmizu** [comment]
あー、社内Scala勉強会です。一応ここpublicなリポジトリなのでURL貼るのはやめておきますが、Slackに貼ります。

**Comment by kmizu** [comment]
言い直しかたがわからなかったのでclose

**Comment by kmizu** [comment]
あと、読み直してみた感じ、より良い表現が思いつかなかったので。
