### ISSUE TITLE
Scala 2.12 だと Java8 のラムダ使われる件

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#192]
> また、関数を定義するといっても、単にFunction0からFunction22までのトレイトの無名サブクラスのインスタンスを 作っているだけです。

https://github.com/dwango/scala_text/blob/8c381c0a97d1f0f12afc78b721b74082be88175d/src/function.md

という記述などが、微妙になるかもしれない？
Scala 2.12 以降、明示的にnewを書いた場合と、そうでなくsyntax suger(?)使った場合は、違うバイトコードが生成されるようになるはずなので

**Comment by xuwei-k** [comment]
つまりこういうの
http://d.hatena.ne.jp/xuwei/20161025/1477381550

**Comment by kmizu** [comment]
脚注で説明を追加する方向へ。

**Comment by xuwei-k** [comment]
Scala公式の仕様での記述はこれだけかな

https://github.com/scala/scala/commit/66b038976d435472b2e5c9720ff2e8cc42177b1a#diff-5d74b019862ed901d7800b4ace79fb5bR1190

> The underlying platform may provide more efficient ways of constructing these instances, such as Java 8's `invokedynamic` bytecode and `LambdaMetaFactory` class.

**Comment by kmizu** [comment]
まあ、その、invokedynamicが生成されるとかは言語仕様的にはどうでもいい（実装詳細）話で、SAM typeとcompatibleになるというのが仕様面での変更点、ってことでいいのではないかと思います。

**Comment by xuwei-k** [comment]
はい。テキスト本体にはあまり詳細な説明は必要ないとは思います
(あくまで、ついでに興味本位で調べたやつを貼っただけ)
