### ISSUE TITLE
Promiseの説明におかしな文章がある

### ISSUE THREAD

**Issue by pocketberserker** [dwango/scala_text#213]
https://github.com/dwango/scala_text/blob/723a8dadbe04758fe5a34589332c38cd016ef604/src/future-and-promise.md#promise%E3%81%A8%E3%81%AF

> なおこの1度だけしか結果が適用されないという特性を活かして、Futureを組み合わせてものが実装できます。

文末が日本語としておかしい気がする？

**Comment by xuwei-k** [comment]
社内GitHubをblameしたところ、途中でなにかミスしたのではなく、最初からこうなってた
