### ISSUE TITLE
scala_textへの単なる感想など、issueやpull requestに当てはまらないフィードバックを受け取る場所が欲しい

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#234]
明らかな間違いとかは issue に報告してもらうかpull requestで修正してもらえればいいですが、単純にここが良かった、ここをもうちょっと良くして欲しいといったカジュアルな感想を伝える場所があると個人的に嬉しいと思いました。ようするに、修正するかどうかはともかくscala_textへの意見を受け取る場所が欲しい。

形態としては、メールとかチャットとか色々あると思いますが、チャットだとなんか反応返さないといけないような気分になってしまいそうなのでメール等で集約できるといいかなと思っています。

**Comment by pocketberserker** [comment]
私はメールだと送信を躊躇してしまうタイプなのですが、読者はどちらの方が投稿しやすいのでしょう…？
（別にメールに反対というわけではない）

別案としてはGoogle forms等を用意するとかですかね？

**Comment by kmizu** [comment]
Google formsが無難かもしれませんね。メールだとどのアドレスに集約するかって話を考えないといけないですし。

**Comment by kmizu** [comment]
管理の手間がなさそうなので、感想書き込み専用issue立ててみます
