### ISSUE TITLE
テキストが対応するscalaVersionの範囲を明確にしておく

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#240]

**Comment by xuwei-k** [comment]
現状は2.11.8で、2.12出たらどうするか？みたいな？

tutとtravis-ciで複数のScalaのversion間でcross buildできるなら、2.11と2.12両方サポートでもいいかもしれないし、面倒なら最新だけ(つまりそのうち2.12だけになる)でも？

**Comment by kmizu** [comment]
テキストの最初の方で対応バージョン明記しておくべきかーみたいな話ですね。2.12出たらどうするか？ってのも当然関わってきますが、その辺はタイミングの問題でしかないので、まあ、とにかく明記しましょうという話です。

**Comment by xuwei-k** [comment]
なるほど？
現状2.11.8でビルドされてるのだから、最低限書くなら2.11.8を書くだけな気はする。
更新の面倒さを軽減するなら、build.sbtへのリンク貼るだけでもいいかもしれないが

https://github.com/dwango/scala_text/blob/12f35d3b10c164fdb35865e41b856d7959290ebc/build.sbt#L8

**Comment by hiroshi-cl** [comment]
その程度の雑な対応であれば現行のこれで十分だったりしないでしょうか？
https://dwango.github.io/scala_text/sbt-install.html

**Comment by kmizu** [comment]
現状、Scala 2.12サポートで決着ついた気がするのでcloseします
