### ISSUE TITLE
練習問題の解答集と問題の間にリンクがないのが辛い

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#25]
http://dwango.github.io/scala_text/answer.html

で、問題本文も添付することで多少探しやすいようになっているけど、回答集の方にリンクあるようにしたい…(練習問題の方にpermalink付加できればよい？gitbookでそうするの、どうすればいいのだろう…）

**Comment by kmizu** [comment]
もっと言えば、練習問題の方に自動的に連番振れるようにしたい…（こちらはさすがに厳しいか？）

**Comment by kmizu** [comment]
問題文の重複を避けるため、問題文のあるページ自体に

```tut:invisible
answer
```
ｚ
で解答を仕込み、問題ページでそのmarkdownへのリンクを貼ることになった（暫定的な対応）
問題文を重複させるのを避けつつ、解答がそのまま見られないようにする（少なくとも一段階処理を多くする）良い案があればそれを採用したいと思います。

**Comment by matsu-chara** [comment]
試せていないのですが、相対リンクでmdファイルへのパスを書くとHTMLへのリンクにしてくれるようです。 https://github.com/GitbookIO/gitbook/issues/535#issuecomment-67390378

**Comment by matsu-chara** [comment]
あ　一番上の方の古い方針へのコメントを書いてました(◞‸◟)

問題文の重複を避ける意図であればソースであるmarkdownへのリンクを貼る方式に :+1: です

**Comment by kmizu** [comment]
Fixed via #76
