### ISSUE TITLE
「Scalaのコレクションライブラリ」を「コレクションライブラリ」に変える

### ISSUE THREAD

**Issue by soukouki** [dwango/scala_text#264]
1. `トレイト` `型パラメータと変位指定` `関数`と続いているところに来るので統一感がない。
2. `Scalaのコレクションライブラリ`だと行頭を見ていると見逃すことがある。

なので、`Scalaのコレクションライブラリ`を`コレクションライブラリ`に変えたほうが良いと思います。

**Comment by kmizu** [comment]
確かに「Scalaの」は余計かもしれませんね。取り除きましょう。
