### ISSUE TITLE
declaration-site varianceの記述を「型パラメータと変位指定」のチャプターに追加してほしい

### ISSUE THREAD

**Issue by c-plus-c** [dwango/scala_text#279]
「Javaとの相互運用」のチャプターでdeclaration-site varianceの話が出てきたが、細かく説明されていなかったため、「型パラメータと変位指定」のチャプターにて変位の話をする際に取り上げてほしい

**Comment by kmizu** [comment]
declaration-site varianceという用語を「型パラメータと変位指定」の章に入れて欲しい、ということでしょうか？元々、「型パラメータと変位指定」で説明しているのは、declaration-site varianceの話で、あえてそういう用語を入れていなかったのですが。
