### ISSUE TITLE
練習問題 「〜〜を出力するコードを作成」という文言から「〜〜を返す関数」へ変更

### ISSUE THREAD

**Issue by matsu-chara** [dwango/scala_text#29]
出題する際の文言についてです。

https://github.com/dwango/scala_text/blob/master/src/control-syntax.md などで

> 以上のコードを利用して、 最初と最後の文字が同じアルファベットであるランダムな5文字の文字列を1000回出力してください。 

とあります。この場合、forで回しながら都度printlnを呼ぶ副作用のある関数を作成する実装方法を最初に思いつく人もいると思うのですが、

> 以上のコードを利用して、 最初と最後の文字が同じアルファベットであるランダムな5文字の文字列が1000個含まれるリストを返す関数を作成してください。 

のようにすれば   `List[String]` を返すような、よりScalaらしい副作用のない関数を作る方法を学びやすいのではないかと思いました。

**Comment by matsu-chara** [comment]
上のような変更がよければ僕が隙をみてやっておきます :ok_woman:

**Comment by kmizu** [comment]
OKです。確かに、その文言の変更で、より良い教育的効果が期待できると思います。

**Comment by matsu-chara** [comment]
了解しました。

その時点での知識でそういうの書けるのかみたいなことが不安になってきたのでチェックしつつ、出来そうなところはやっていく感じで行きますー

**Comment by kmizu** [comment]
関連 pull req #54
