### ISSUE TITLE
sbt 1.0 と 0.13 の使い分けや違いについて書く

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#293]
https://github.com/dwango/scala_text/pull/292#issuecomment-321925444

細かいことまで書こうとすると、ある意味きりがないが、1.0と0.13どう使い分ければいいか、最低限わかるまで書く?(あるいはそれがわかるページへのリンクを貼る)

Java8必須とか、ビルドされてるScala version自体が違うとか、そういうことも多少書いた方がいいかもしれない(?)

本文で1.0推奨する、0.13の記述を消すのは、playframework が完全に対応した頃だろうか(?)

**Comment by xuwei-k** [comment]
sbtのビルドファイルのやつをtutでチェックするのを復活させる、というタスクもあるな

https://github.com/dwango/scala_text/pull/118

**Comment by xuwei-k** [comment]
もし1.0に移行する場合、scoverageやscalastyleなどのsbt plugin紹介してる記述があるから、それらもsbt 1.0対応versionにあわせる、なども必要か

**Comment by xuwei-k** [comment]
playが2.6.6からsbt 1.0対応したので、もう1.0前提で0.13の記述しない、でいいかもしれない?

**Comment by kmizu** [comment]
1.0.2でコンソールの表示とか修復されたみたいですし、1.0系前提でもいいかもしれませんね。
