### ISSUE TITLE
valで再代入できるかのように誤認させる恐れがある説明がある

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#311]
[basic.md](https://github.com/dwango/scala_text/blob/b4e97ca6b273e4d98787687712547aa9a519b6c1/src/basic.md)において、

> 定義した変数の型はIntと推論されたので、その後、別の型、たとえばString型の値を代入しようとしても エラーになります。

とありますが、ここでは `val` を使っているため、Intであろうとエラーになるので、あまり適切ではない説明のように感じます。
直前や直後で `val` は再代入不可と説明していますが、ここの説明のために読者を惑わせてしまう恐れがあります。

**Comment by kmizu** [comment]
最初に、val / var の違いを説明していますし、その後にも説明があるのでさすがに勘違いする読者はいないような気がします。ただ、説明として微妙という点はその通りかなとも思うので、修正はします。
