### ISSUE TITLE
説明と画像の不一致

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#314]
[IDE.md](https://github.com/dwango/scala_text/blob/9003ca4aa0e86f9dc2bb548bbe2fafe430bff4c3/src/IDE.md)に

> 赤枠で囲った箇所全てにチェックを入れます

と本文中にはありますが、画像には赤枠がありません。

**Comment by kmizu** [comment]
おそらく、初期の原稿からスクリーンショットを更新した際に起こったミスですね。ご指摘ありがとうございます。スクリーンショットは、メンテナンスが割と面倒なので（特にIntelliJ IDEAは頻繁にスプラッシュウインドウや内部の細かい項目が変わる傾向がある）、今後どうしようかちょっと考えています。
