### ISSUE TITLE
式の説明の正確さ

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#315]
明確な誤りとするかは微妙ですが、[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)で

> 次に「式（Expression）」は、プログラムを構成する部分のうち、評価することで値になるものです。

とあります。
これによると、`throw`式や `???` などを評価しても値が取れなければならないことになりますが、Scalaではこれらも何らかの値を取るという考え方になっているのでしょうか。

**Comment by bleis-tift** [comment]
`return`式もですね。

> if式に限らず、Scalaの制御構文は全て式です。つまり必ず何らかの値を返します。

ともありましたが、`throw`式や`return`式など、値を返さない式もあります。

**Comment by hiroshi-cl** [comment]
鋭い指摘だと思います。ご指摘の通り、これらの式には、

- 結果を変数に束縛できるなど、外見的にはあたかも値を返すかのように扱える一方で
- 実際には値を返す実行パスが存在しない

という特徴があり、そのうちの前者しかカバーできていない記述になっています。

しかしながら、個人的には、この節が式と文の対立の大雑把な理解を目的としていることを鑑みると、このくらいの精密さが良いと思うのですがいかがでしょうか？

**Comment by bleis-tift** [comment]
以降でフォローがあるならばそれでもかまわないと思います。
ないのであれば、そういうフォローを入れるか、この部分を加筆するかした方がいいのではないでしょうか。
例えば私自身、Scalaの仕様を読んで初めて`return`式の結果型は(`return x`の`x`の型ではなく)`Nothing`であることを知ったのですが、この種の誤解を招きかねないかな、と思います。

**Comment by kmizu** [comment]
> とあります。これによると、throw式や ??? などを評価しても値が取れなければならないこと
> になりますが、Scalaではこれらも何らかの値を取るという考え方になっているのでしょうか。

これはより正確に説明すると、評価がstuckしなければ値が取れる、ということになるかと思います。

「評価が成功すると値になるものです」辺りが、簡潔で、かつ、正確な説明でしょうか（そうすると、評価が成功するとはどういうことなのか説明する必要がありそうな気もしますが）。

**Comment by bleis-tift** [comment]
> 評価が成功すると値になるものです」辺りが、簡潔で、かつ、正確な説明でしょうか

これでいいと思います。
値ではなく型に着目して、「型が付くもの」としてしまうのも考えましたが、上の方が分かりやすいと思います。
成功、失敗については、「例えば、評価の結果例外が投げられた場合などが失敗です」のような補足(脚注とか)があれば十分(別になくてもいいようにも思う)ではないでしょうか。
