### ISSUE TITLE
implicit parameterの解説でのMonoidの説明を、Monoidという単語を使わずに行う

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#32]
* 動機：圏論的な用語をimplicit parameterの説明のときに極力出したくない
* See: 
  * https://twitter.com/kmizu/status/695888613012156416
  * https://twitter.com/lyrical_logical/status/695894156531478528
  * https://twitter.com/lyrical_logical/status/695895462457405440
* 説明の最後に、～という性質を満たしたものがMonoidと呼ばれます、という感じにできればよい。

**Comment by xuwei-k** [comment]
Appendableみたいな言葉出すと(?)、Monoidという単語を少しでも聞いたことある人にとっては、場合によっては逆にわかりづらくなる可能性ある気もしますけど、どうなんですかね・・・。
もうちょっと説明に工夫の余地あるなら、改善すること自体は賛成です。

あと、どうでもいいツッコミとしては、Monoidは圏論というより、そこに比べれば多少初等的な数学の範囲な気がします
(べつに圏論詳しいわけではないので、捉え方によって色々ありそうですが)

**Comment by xuwei-k** [comment]
> 多少初等的な数学の範囲

群論では、というツッコミを(社内から)もらった

**Comment by matsu-chara** [comment]
入門用のテキストですし、モノイド知ってるような人なら「モノイドって単語使うの避けたのかな」くらいで理解してもらえそうな気がしています。

**Comment by kmizu** [comment]
とりあえず、テキストの書き方として、

```scala
trait Additive[T] {
  def add(x: T, y: T): T
}
```

という二つのトレイトを用意して、これだけだと要素数が0のときの合計値が計算できない！ので

```scala
trait Zero[T] {
  def zero: T
}
```

を出して、最後に

```scala
trait Monoid[T] extends Additive[T] with Zero[T]
```

と定義する方向にもっていこうかと考えています。

**Comment by xuwei-k** [comment]
Zeroだけ独立させると、typeclassとしてのlawが定義できなかったり、そもそも一意に定まらない(?)ので消そう、みたいな経緯でscalazでは消えたけど、

そのあたりを考えると、(Additiveはあっても)Zeroはないほうがいいのか、そんなツッコミや疑問を持つ人多くない(or 重要じゃない)と想定して気にせず、Zeroは独立させてしまうか？

という論点が(?)

**Comment by kmizu** [comment]
lawはAdditiveとZeroをmix-inしたMonoidのレベルで定義できれば別にいいのでは？（ので、別にZeroを独立させても問題ない）と思いました。
> そもそも一意に定まらない(?)
こっちのツッコミはちょっとよくわからなかったです。

**Comment by xuwei-k** [comment]
足し算のゼロは `0` だけど、掛け算のゼロは `1` とか。 **Additiveと組み合わせて考えないと一意に定まらない** ですかね

**Comment by xuwei-k** [comment]
一意に定まらないといけない、という暗黙の前提もおいて話してたけど、その前提なしでいい場合もありそう(?)

**Comment by xuwei-k** [comment]
> AdditiveとZeroをmix-inしたMonoidのレベルで定義できれば

それでいいならいいんですけど、だったら独立させる必然性もないかな、程度の意見ですかね

**Comment by kmizu** [comment]
> 足し算のゼロは 0 だけど、掛け算のゼロは 1 とか。 Additiveと組み合わせて考えないと一意に定まらない ですかね

なるほど。その意味では確かに一意には定まりませんね。

**Comment by kmizu** [comment]
> それでいいならいいんですけど、だったら独立させる必然性もないかな、程度の意見ですかね

独立させるかは自分もまだ迷っています。名前は変えるのはだいたい決めていますが。

**Comment by kmizu** [comment]
そうだ。`Additive`というような名前をあえて使う意味について考えてたのですが、それこそ意味を一意に決定できるという良い効果があるのではないかと。

たとえば、`Monoid[Int]` のインスタンスを定義しろ、だけだと、乗算も(zero:1, mplus: +)、加算も(zero:0, mplus:+)OKになっちゃいますが、`Additive[Int]`のインスタンスを定義しろ、だと、名前から暗黙のうちに乗算モノイドを排除できてるのでいいのではないかと。で、乗算モノイドは別途`Multitive[T]`とか定義する。

**Comment by pocketberserker** [comment]
それを採用するならMonoidにもっていく部分は削る、という認識であってますか？
AdditiveとMultitiveが別物な以上、Monoidにするのは厳しい認識でいますが。

**Comment by kmizu** [comment]
そうですね。おそらく、削ることになるかと思います。

> Monoidにもっていく部分は削る

**Comment by xuwei-k** [comment]
なるほど。それならそれでありな気はします > Monoid削ってAdditiveとMultitiveというかたちで書く。

あとは、個人的に型クラスの理解深めさせるなら、play-jsonのReadsとか、具体的な型クラスを、もっといくつか紹介したほうがいい気がしているけれど、全体のバランス考えるとどの程度型クラスの説明に割くべきなのか難しい気はする・・・(?)

**Comment by pocketberserker** [comment]
トレイト応用編みたく、型クラスの実用的な例という個別の節にしてしまっても良いのでは？

**Comment by xuwei-k** [comment]
https://github.com/dwango/scala_text/pull/34 で書き換えたのでclose
