### ISSUE TITLE
ORパターンの説明の不正確さ

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#322]
[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)のmatch式の説明で、

> 下記のように|のパターンマッチで変数を使った場合はコンパイルエラーになります。

とありますが、例えば

```scala
xs match {
  case List(0|1, a) => a
  case _ => -1
}
```

は通るようです。
ORパターンの中では値は取り出せないようですが、ORパターンの外であれば取り出せるということだと思います(仕様は未確認)。

**Comment by bleis-tift** [comment]
ちなみに、F#ではORパターンの中であろうが型さえ合っていれば取り出せるのですが、これをできないようにしている理由は何かあるのでしょうか。

```fsharp
// OK
let f = function
| 0::xs
| 1::xs -> xs
| _ -> []
```

**Comment by kmizu** [comment]
> ORパターンの中では値は取り出せないようですが、ORパターンの外であれば取り出せるということ
> だと思います(仕様は未確認)。

これについてはおっしゃる通りですが、そこまで説明しようとすると、パターン（case等の中で使える構文全体）自体について詳細な説明が必要になるので、ここでそれをするのは苦しいかなという気がしています。

> ちなみに、F#ではORパターンの中であろうが型さえ合っていれば取り出せるのですが、
> これをできないようにしている理由は何かあるのでしょうか。

できないようにしている理由については見たことがありませんが、単純に、保守的にチェックした方が楽だからくらいではないかと思います（型をみなくても変数パターンとして合法か判定できますし）

**Comment by bleis-tift** [comment]
結局今の説明では、「ORパターンでは値は取り出せない」という伝わり方しかしないので、いっそのこと「ORパターンでは値が取り出せない場合がある。詳細は今は難しいので後で(もしくは仕様のここを読め)」とかでもいいと思います。

> 型をみなくても変数パターンとして合法か判定できます

がよくわかりませんでした。
例えば、

```fsharp
let f = function
| (x, 0)
| ([], x) -> x
| _ -> failwith "oops!"
```

のような場合、F#ではコンパイルエラー・・・あー、ScalaではAnyに落とせばいいということですかね。

**Comment by kmizu** [comment]
対象読者は、Scala初学者ですし、そもそもScala熟練者であっても、ネストしたパターンの中でORパターンを使う例というのは見たことがないので、そういう人はさすがに想定しなくていいと思います。

厳密な仕様は言語仕様を読め、でもいいのですが、それ言い出すと、全ての箇所にそれ付ける必要があるので、あんまりそれはやりたくないです。


> let f = function
> (x, 0)
> ([], x) -> x
> _ -> failwith "oops!"

F# には詳しくないのですが、それがコンパイルエラーになる原因というのは何でしょうか？おそらく型がらみのエラーではないかと推測するのですが。Scalaの場合だと、単純にORパターンは変数を束縛できない、という構文的な判定でいいのでより楽なのではと思います（F# でコンパイルエラーになる原因が構文的なものであれば、自分の推測は当たってないのですいません）。

**Comment by kmizu** [comment]
ちなみに、ORパターン、Scala Language Specificationでは、patern alternatives

https://www.scala-lang.org/files/archive/spec/2.11/08-pattern-matching.html#pattern-alternatives

として言及があり、

> They may not bind variables other than wildcards

という風に非常にシンプルなルールになっています。F#の場合、できる場合とできない場合の判別には、より複雑なルールが必要なように思えます（別にどっちがいいとかいう話ではなく、ルールが単純化できるということについて言及しているだけです）

**Comment by bleis-tift** [comment]
> 型をみなくても変数パターンとして合法か判定できますし

の部分を誤読していました。
「Scalaで実装するとなったとしても、型を見る必要はない」と読んでいましたが、「ScalaではORパターンで値が取り出せないので型を見る必要はない」ということですね。

> 対象読者は、Scala初学者ですし、そもそもScala熟練者であっても、ネストしたパターンの中でORパターンを使う例というのは見たことがないので、そういう人はさすがに想定しなくていいと思います。

コマンドライン引数のパーサーをよく書くので、ショートオプションとロングオプションでORパターンを使って値を取り出すようなコードが書けるとありがたいのですが、普通は何らかのライブラリを使いますね・・・

関係ないところまで答えていただいてありがとうございました。
