### ISSUE TITLE
メソッド定義の本体について

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#324]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)のメソッド定義において、

> メソッド本体が1つの式だけからなる場合は、(略)と書けます（実際には、こちらの方が基本形で、`= {}`を使ったスタイルの方が`{}`内に複数の式を並べて書けることを利用した派生形になりますが、前者のパターンを使うことが多いでしょう）。

とあります。
しかし、[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)の`{}`式にもあるように、`{}`も「1つの式」です。
`{}`式が1つの式ではないとしたら、複数の式を組み合わせて使う`if`式など、コンパイル時定数や変数くらいしか1つの式というものはなくなってしまいます。
当然そういうことではなく、`if`式を始めとした複数の式を組み合わせて使う式が使えます。

せっかくcontrol-syntax.mdの方で`{}`は構文ではなく、単なる式だ、としているのに、メソッド定義の本体部分でこのような説明になるのは整合性が取れていないのではないでしょうか。

**Comment by kmizu** [comment]
> メソッド本体が1つの式だけから

云々については、何故こう書いてしまったのか自分でもよく思い出せず。両方共自分が書いたのに、ちょっと変ですね。直します。
