### ISSUE TITLE
オブジェクトの説明が説明になっていない

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#326]
[object.md](https://github.com/dwango/scala_text/blob/5c5d90de5b68e1d6fa1340cf97c59d778b2243d6/src/object.md)の冒頭で、

> `object`キーワードによって定義したオブジェクトもオブジェクトであるため、メソッドやフィールドを定義することができます。

とありますが、説明になっていません(オブジェクトもオブジェクト)。

オブジェクトにメソッドやフィールドを定義できることの説明も足りていないように思います。
Javaプログラマからすると、オブジェクトだからメソッドやフィールドが定義できるのではなく、あくまで定義するのはクラスであり、それを実体化してオブジェクトを得ている感覚だと思うので、「オブジェクトだからメソッドやフィールドが定義できます」は説明として弱いです(こっちは意見ですが、面倒なので混ぜました)。

**Comment by kmizu** [comment]
最初の引用文の点については改善したいと思います。

ただ、オブジェクト指向言語において、（非staticな）メソッドを持つ主体はオブジェクトであり、クラスではない（クラスは単なる雛形ですし、）、というのは常識に属する事項だと私は思うので、オブジェクトを直接定義できるなら、そこにメソッドやフィールドが定義できるのも自然だというのが私の感覚です（Javaにはそういう構文サポートがないだけであって）。

**Comment by bleis-tift** [comment]
後半は意見なので、そのままでも構いません。
個人的には、Javaで育った人間がそのあたりを自然と感じられるかは疑問ではありますが。。。
