### ISSUE TITLE
for式についての説明

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#333]
[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)のfor式の説明で、

> Scalaにはfor式という制御構文がありますが、これはJavaの制御構文と似た使い方ができるものの、全く異なる構文です。

とありますが、

Scalaにはfor式という制御構文がありますが、これはJavaの制御構文である拡張for文と似た使い方ができるものの、全く異なる構文です。

のようにどの構文と対応付いているのか明示したほうがいいと思います。
また、「全く異なる構文です」というのも言いすぎな気がします。
Scalaのfor式は、Javaの拡張for文のようにループのみに特化しておらず、より様々な制御に対応している構文という認識です。
あくまでループへの対応も様々な制御の一つであり、「全く異なっている」かというとそうでもないと思っています。

**Comment by kmizu** [comment]
拡張for文については、確かに言及があった方が良さそうなので、そうするようにします。

「全く異なる構文です」については、Javaから来た人は、ループのための構文というイメージに引きずられやすいので、そこからいったん離れて、もうちょっと抽象的なもとして見て欲しいという意図があります。適用例の一つとしてループがあるのは確かですが。

**Comment by kmizu** [comment]
Closed via #361
