### ISSUE TITLE
match式についての説明

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#334]
[control-syntax.md](https://github.com/dwango/scala_text/blob/daf85006396150fffaf43d575a1ae34037c379e5/src/control-syntax.md)のmatch式の説明の書き出しが、

> `match`式は使い方によって非常に幅のある制御構造です。

となっており、直後を読めば分かるとはいえ、親切ではない(何も言っていないに等しい)と思います。
せめて、

`match`式は多分岐を行う制御構文ですが、Javaの`switch`文以上に様々なことができます。

のようにした方がより親切ではないでしょうか。

**Comment by bleis-tift** [comment]
> match式を使うときは、漏れがないようにするために、ワイルドカードパターンを使うことが多いです。

とありますが、これは出来る限り避けるべきプラクティスだと思います。
例えば、sealedなcase classが増えた時に、ワイルドカードパターンを使っているとコンパイラが指摘してくれなくなるため、できる限りワイルドカードパターンに頼らずに書くべきではないでしょうか。
もし、Javaのswitchとしてのmatchに限定した話であれば、それを明記したほうがいいと思います。

**Comment by kmizu** [comment]
> とありますが、これは出来る限り避けるべきプラクティスだと思います。
> 例えば、sealedなcase classが増えた時に、ワイルドカードパターンを使っているとコンパイラが
> 指摘してくれなくなるため、できる限りワイルドカードパターンに頼らずに書くべきではない
> でしょうか。

sealed case classを使っていて、かつ、ifによるガード条件がない場合は、網羅性チェックをはたらかせるために避けるべきと言えますが、そうでない場面も多いです。いくつか、ワイルドカードパターンで漏れがないようにした方がいい場合を挙げてみます：

- 文字列の比較などに使う場合
- ガード条件（if）を使う場合
- 抽出子を使う場合
  - 正規表現パターンなど
- パターンに関する不変条件が複雑で、網羅性チェックによってうまく近似できない場合
 
もちろん、警告を消すためだけにワイルドカードパターンを使うことは、よくないこともありますが、一般論としては、ワイルドカードパターンで、列挙した以外のケースを扱う方が良い場合も多いと私は思います。

**Comment by bleis-tift** [comment]
個人的には、マッチしないことを表す場合に `other` や `notMathced` のような変数パターンを使うことが多かったのですが、これはこれで問題もある(未使用変数警告が出る)ため、確かに言い切るのは難しいと思います。
ただ、今の表現だと「漏れがないようにしたい(≒警告を消したい)場合はワイルドカードパターンを使う」という行動につながってしまうようにも思うため、注意書きのようなものでもいいのであったほうがより親切かな、と思いました。
