### ISSUE TITLE
複数のコンストラクタについて

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#336]
[class.md](https://github.com/dwango/scala_text/blob/e4dd1053ada11c9350fa804306ae7abe27d20b79/src/class.md)のクラスの定義では、基本的にはScalaでは複数のコンストラクタは定義せず、プライマリコンストラクタしか使わない、というようなことが書いてあります。
それはそれでいいのですが、objectのapplyメソッドを定義したり複数オーバーロードしたりはするはずであり、「その代わり、objectのapplyメソッドとして定義することが多いです」のような脚注を入れた方がこれまで複数のコンストラクタを定義してきた人にとって引っかかりが起きにくいのではないでしょうか。
また、非プライマリなコンストラクタではなくobjectのapplyメソッドを使う理由(利点)もどこかに説明があると嬉しいです(こちらは個人的な興味ですが)。

**Comment by kmizu** [comment]
Closed via #360
