### ISSUE TITLE
抽象メンバーについて

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#348]
[trait.md](https://github.com/dwango/scala_text/blob/29b1a5b099b632cf9b42e12775514672b2d84a24/src/trait.md)の「クラスパラメータ（コンストラクタの引数）を取ることができない」に

> インスタンス化のときに抽象メンバーを実装をすることでトレイトに値を渡すことができます。

とありますが、抽象メンバーについての説明がここまでにありません。

**Comment by kmizu** [comment]
確かに、抽象メンバーについての說明が抜けていたようです。対応します。
