### ISSUE TITLE
型パラメータ名について

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#355]
[type-parameter.md](https://github.com/dwango/scala_text/blob/73a13909d84b0543de3d90977a6c45a5db704ebf/src/type-parameter.md)ですが、Scalaでは型パラメータにA, B, ...と付ける習慣があることに触れたほうが親切だと思います。
メインターゲットがJavaなので、型パラメータにはEなどを付けることに慣れている人が多いのではないでしょうか。

**Comment by xuwei-k** [comment]
> Scalaでは型パラメータにA, B, ...と付ける習慣

そのはずだったけれど、少し前に公式がこんなことやりだしたので

https://github.com/scala/scala/commit/7e933d5b5a4c1c8795b74e67e2148c6fc4ca19a6

公式はどうしたいのか若干謎ではあるけど、あの慣習完全になくなってるわけでもないので、触れることに反対でもない(けど自分で書くのは面倒)くらいな気持ち

**Comment by bleis-tift** [comment]
そんなことになっていたとは知りませんでした・・・
時間があったらPRにしてみます(が、中の人がやった方が統一感あっていいよなぁ、とも)。

**Comment by kmizu** [comment]
補足入れてみました。
