### ISSUE TITLE
複数戻り値について

### ISSUE THREAD

**Issue by bleis-tift** [dwango/scala_text#363]
[type-parameter.md](https://github.com/dwango/scala_text/blob/73a13909d84b0543de3d90977a6c45a5db704ebf/src/type-parameter.md)で、

> メソッドから複数の値を返したい、という要求はプログラミングを行う上でよく発生します。そのような場合、型パラメータが無い言語では、
> 
> * 片方を返り値として、もう片方を引数を経由して返す
> * 複数の返り値専用のクラスを必要になる度に作る
> 
> という選択肢しかありませんでした。

とありますが、例えばGoでは多値を実装しているため、選択肢がこれしかないというのは誤りです。

**Comment by kmizu** [comment]
確かにそうですね。そもそも、Schemeなど、もっと古い言語にも多値はあるので。意図としては、多値のネイティブなサポートが無い言語では、そのような選択肢しかないというものでした。修正します。

**Comment by bleis-tift** [comment]
Schemeは動的型付き言語なので、型パラメータがそもそも・・・ということでGoを持ち出しました;-)
