### ISSUE TITLE
type-parameterの演習問題のStackのメソッド定義について

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#37]
https://github.com/dwango/scala_text/blob/f760890047eace599cd32546cc0c7d66075914b4/src/type-parameter.md#演習問題

immutableといっているし、(いずれにせよmutableだとしても) isEmpty などは副作用はないはずなので、
`def isEmpty()` ではなく `def isEmpty` にしておくべきではないか？

`def pop()` もある意味同様の問題があるが、空の場合は例外投げるので、副作用あると捉えることも可能(?)なので、微妙に別問題？

気がついてないだけで、同様の問題は他にもあるかもしれない

**Comment by kmizu** [comment]
```
def pop()
```

も同様ですね。空の場合例外投げるというのは、副作用というより`pop()`が部分関数（Scalaの意味ででなく、数学的な意味での)であることを表しているだけなので（部分関数であることを表現するために例外を使用しているというべきか？）。

**Comment by kmizu** [comment]
意味的には、値が定義域に入っていないのでたぶん評価がstuckするべきなのですが、それを表現する方法がないので代わりに例外を使っているというべき？

**Comment by xuwei-k** [comment]
https://github.com/dwango/scala_text/pull/41 で修正したのでひとまずclose
(他にもあれば、再openか、別途issueたてる)
