### ISSUE TITLE
型クラスの章のレビューを書くIssue

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#400]
https://dwango.github.io/scala_text/

に「型クラスへの誘い（β版）」として追加したが、まだレビューしてもらっていないので、レビューしてくださると助かります。コメントはこのIssueに書き込んでください。

**Comment by hiroshi-cl** [comment]
いくつか気になった点コメントします

> ここで、Listのsizeを計算するのは若干効率が悪いですが、その点については気にしないことにします。

本筋と関係ない話なら脚注で補足する程度に留めるのがいいかなと思いました。
それはさておき、話の流れを察するとここは次のコード例同様 `foldLeft` で `length` を求めるコードを例を示して、「Listのsizeを計算するのは若干効率が悪いですが、一般化しやすいようにこうします」のように言うのがいいんじゃないかなと思いました。

> 残念ながら、このコードはコンパイルを通りません。何故ならば、 A 型の値を A 型で割ろうとしているのですが、その方法がわからないからです。

`lst.foldLeft(m.zero)((x, y) => m.plus(x, y)) / length` のことだと思うのですが、この式の前半が重すぎるのかパッと見でわかりにくい気がします。以下のように型注釈も補って少し冗長に書いてみると良い気がします。

```
  val length: A = lst.foldLeft(m.zero)((x, _) => m.plus(x, 1))
  val sum: A = lst.foldLeft(m.zero)((x, y) => m.plus(x, y))
  sum / length
```

> ここで、Additive をより一般化して、

手前に改段落が必要だと思います。

> ここで、 Nums は、対話環境でコンパニオンクラス/オブジェクトを扱うために便宜的に作った名前空間であり、通常のScalaプログラムでは必要ありません。

通常のScalaプログラムではどうするのでしょう？パッケージでしょうか？
名前空間に切ってモジュール化すること自体は普段から必要なことですしちょっとモヤッとします。

> 別のアルゴリズムをライブラリ化した例を、Scalaの標準ライブラリから紹介します。

この章には節の区切りが全くなくてつらいのでこの辺で小見出し入れて小休止ほしいですね。。

> オブジェクトをシリアライズするメソッド string を定義したいとします。

「オブジェクトを *文字列に* シリアライズするメソッド」くらい言った方が誤解等が少ない気がします。

> 次はより複雑な例を考えてみます。

ここから始まるシリアライズの節は内容はいいと思うのですが、説明のブラッシュアップが足りない気がします。後日改めてコメントしたいです。

> 一方、今回用いた手法では、後付けでシリアライズする型を追加でき、かつコンパイル時にその正当性を検査できるのです。
> ここまでで紹介したように、型クラス（≒implicit parameter）は、うまく使うと、後付けのデータ型に対して既存のアルゴリズムを型安全に適用するのに使うことができます。

この *後付け* というのは、この章における重要なメッセージだと思います。しかしながら段落の最後で取ってつけたように言われて、その次の段落で「ここまでで紹介したように」とまとめられてもあまり共感できる気がしません。
例えば、シリアライズの節のコード例は詰め込みすぎなので、 `MyKlass`, `MyKlassSerializer` の例を切り離して後付けに関する1節を作ってみてはいかがでしょうか。
(ローカルな名前空間じゃなくてクラスに後付けするとかそういうちょっと違う意図なのかもしれないですが)

**Comment by kmizu** [comment]
返事が遅くなってすいません。

> 本筋と関係ない話なら脚注で補足する程度に留めるのがいいかなと思いました。
確かに。

> 通常のScalaプログラムではどうするのでしょう？パッケージでしょうか？
> 名前空間に切ってモジュール化すること自体は普段から必要なことですし
> ちょっとモヤッとします。

REPLだと、同一ファイル内であることが認識されないために、 `Nums` で同一モジュールに
属することを明示的に書くことが必要である、というのが理由なのですが、それが明記されていない
のでわかりにくくなっていますね。直します。

> この章には節の区切りが全くなくてつらいのでこの辺で小見出し入れて小休止ほしいですね。。

了解です。

> この 後付け というのは、この章における重要なメッセージだと思います。しかしながら段落の
> 最後で取ってつけたように言われて、その次の段落で「ここまでで紹介したように」
> とまとめられてもあまり共感できる気がしません。

なるほど。ちょっとこの辺は構成を考え直してみます。
