### ISSUE TITLE
「ScalaのAPIドキュメント」へのリンク先について

### ISSUE THREAD

**Issue by glabra** [dwango/scala_text#422]
#419 に関連した話ですが、「ScalaのAPIドキュメント」を参照している箇所全てに同様の問題が存在します。

つまり、あるAPIのドキュメントではなく、root packageのドキュメントにリンクが貼られています。

**Comment by kmizu** [comment]
すいません。これは、ちゃんと対応して直しますね。

**Comment by kmizu** [comment]
@glabra リンクを全部修正しました。ご報告ありがとうございます。
