### ISSUE TITLE
演習： カウントダウンラッチ の解答例について

### ISSUE THREAD

**Issue by arushiro** [dwango/scala_text#423]
Future/Promiseについて(https://dwango.github.io/scala_text/future-and-promise.html)
の章の「演習： カウントダウンラッチ」についてですが、

>FutureやPromiseの便利な特性を利用して、0〜1000ミリ秒間のランダムな時間を待つ8個のFutureを定義し

と問題に書いてあるのですが、

`val waitMilliSec = random.nextInt(1000)`

と解答例にありました。

 `Random.nextInt(n: Int): Int` は

>between 0 (inclusive) and the specified value (exclusive)

(https://www.scala-lang.org/api/2.12.0/scala/util/Random.html)
な Intの値を返すので、
`random.nextInt(1000)` は0～999の値しか返さず、問題の条件に適していないかと思われます。

**Comment by kmizu** [comment]
区間として、1000を含むかは書いていないので、どっちでもいいかとも思うのですが、1000を含むとする読み方の方が多そうだとは思うので、直しますね。
