### ISSUE TITLE
型パラメータの誤字(Int → String)

### ISSUE THREAD

**Issue by blackbracken** [dwango/scala_text#459]
https://github.com/dwango/scala_text/blob/master/src/introduction-to-typeclass.md#オブジェクトのシリアライズ
整数と文字列のSerializer実装のコードで`implicit object StringSerializer extends Serializer[Int]`となっていますが, `Serializer[String]`だと思います

**Comment by kmizu** [comment]
@blackbracken 誤字のご指摘ありがとうございます。早速修正するpull request作っておきました。
