### ISSUE TITLE
averageメソッドの除算が重複

### ISSUE THREAD

**Issue by Kyou13** [dwango/scala_text#464]
[型クラスへの誘い - averageメソッド](https://github.com/dwango/scala_text/blob/master/src/introduction-to-typeclass.md#averageメソッド)
```scala
def average[A](lst: List[A])(implicit m: Additive[A]): A = {
  val length: Int = lst.length
  val sum: A = lst.foldLeft(m.zero)((x, y) => m.plus(x, y)) / length
  sum / length
}
```

`sum`への代入部分において,`length`による除算は不要ではないでしょうか。

**Comment by kmizu** [comment]
その通りですね。直します。ありがとうございます。
