### ISSUE TITLE
travis-ciが失敗する

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#479]
何もしていないのに2019年1月頃から通らなくなった。今のところ詳細原因不明。

**Comment by kmizu** [comment]
ログから表面的な原因ぽいのとか何かあったりします？

**Comment by xuwei-k** [comment]
tutの実行中 or 実行後？で固まってるくらい・・・？ 🤔 
ローカルだと再現しない気がする、謎

**Comment by kmizu** [comment]
いっそのこと、CircleCIでビルド設定作り直す、というのもありえますが…。

**Comment by xuwei-k** [comment]
まぁtravis-ci自体が直接的 or 間接的な原因なのかは何もわかってないので、なんとも言えないですけど、他のCIでうまくいくなら(原因不明なtravisでデバックを頑張るより作り直すほうがコスト低いなら)、それでも・・・ 🤔
