### ISSUE TITLE
oracle-java8-installerでtravis-ciがこける

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#487]
- #486 のビルドログを見ると、Java 8をインストールしようとしてこけている
  - 他のビルドで通っているのは、おそらくキャッシュが残っているため
- Java 11の正式リリースにともなって、（おそらく）ダウンロードURLが変わったため
- workaroundはあるが、そもそもOracle Java 8は無償サポート切れな気がする
- 解決策
  - (a) OracleのOpenJDK 11を入れるようにする
  - (b) [Amazon Corretto](https://aws.amazon.com/jp/corretto/) (8 or 11) を入れるようにする
  - (c) [AdoptOpenJDK](https://adoptopenjdk.net/) (8 or 11)を入れるようにする

**Comment by xuwei-k** [comment]
oracle-java8-installer、前からよく(他のリポジトリでも)失敗することあるので、(最新の8を入れることにこだわらなければ)単に該当行を消して動く(?)なら、消しちゃっていいと思います

**Comment by kmizu** [comment]
なるほど、元々失敗することがよくあったんですね。とりあえず、Corretto 8を入れる方向（？）で試してみようかと思います。

**Comment by kmizu** [comment]
oracle-java8-installer 消して、`jdk:openjdk8` にするのを #486 でやったらうまく行ったのでcloseします
