### ISSUE TITLE
練習問題と解答(answer.md)で文章の重複がある

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#55]
* 元々は解答例を別の場所に移したかったからなのだが、`tut:invisible`使ってその場で書く
  * 解答例を移したら、`answer.md`から順次削除
* 関連： ref #29

**Comment by xuwei-k** [comment]
ref https://github.com/dwango/scala_text/pull/54

**Comment by kmizu** [comment]
Fixed via #76
