### ISSUE TITLE
IDEへのスクリーンショットを再度撮り直し（IntelliJ IDEA 2016）

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#57]
* [IntelliJ IDEA 2016がリリースされた](http://blog.jetbrains.com/idea/2016/03/intellij-idea-2016-1-is-here/)ので、それにともないスクリーンショットを更新する
* 少なくとも、スプラッシュスクリーンが変更されたのは確実
  * 最近、現行バージョンのIntelliJ IDEAのスクリーンショット撮り直したばかりなのに（泣）

**Comment by kmizu** [comment]
みたところ、スプラッシュスクリーンと起動画面以外変更はなさそうなので、その部分だけ撮り直しすればよさそう…。

**Comment by xuwei-k** [comment]
撮り直すにしても、研修開始直前でよさそう(何度もやることになるのを防ぐため)

**Comment by kmizu** [comment]
それは確かにそうですね…。とりあえず、既に撮り直してしまった部分については、テスト通ったら後でマージしてもらえればと。

**Comment by xuwei-k** [comment]
https://github.com/dwango/scala_text/pull/59
