### ISSUE TITLE
各練習問題に一意のIDを振りたい（自動生成されたものではなく）

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#58]
* 現状でも、見出しを元に自動的にIDを振ってくれるが、見出し名が変わると参照元も変えなくてはいけないのがいけてない
* [この辺](http://toolchain.gitbook.com/syntax/markdown.html)をみると

```
# 見出し名 {#見出しID}
```

のようにすることで、成果物のhtmlの中で特定の見出しを参照するときに、 `hoge.html#見出しID`と参照することができる。

* 試験的にブランチ作って試してみたのが、[これ](https://github.com/kmizu/scala_text/commit/b995ff969e3ec21ef159582eba36225b59061653) で、成果物のHTMLに対しては確かにリンクを張ることができた
  * しかし、元のmarkdownをgithub上で参照したときに、 `#見出しID`がそのままレンダリングされてしまう（汚染されてしまう）という欠点があるので、どうするかは微妙なところ…。
* いいアイデア求む

**Comment by y-yu** [comment]
GitHubでみたときに見た目が崩れるという議論でしたら、次のような脚注を入れる記法がすでにGithubでは正しく表示されていません。

```markdown
this is a pen[^pen].

[^pen]: I like this.
```

このような脚注は、例えば下記のファイルで使われています。

https://github.com/dwango/scala_text/blob/master/src/introduction-to-scala.md

このように、もはやGithubのMarkdownの表現力を越えたMarkdownを使用しているので、Githubにおける見た目はあまり気にしなくてもよいのではないかと思いました。

**Comment by kmizu** [comment]
@y-yu ありがとうございます。確かに、脚注記法正しく表示されてないですね。じゃあ、気にしないで、

```
# 見出し {#見出しID}
```

の記法（GitBookでサポートされている）を使います。

**Comment by xuwei-k** [comment]
これ、方針は決まって、それなりに対応させてうまくいってるので、閉じてよさそう？
それとも全部の問題と解答を書き終わってから閉じる？(もとのissueの範囲と微妙に方向性違くなるが)

**Comment by kmizu** [comment]
そうですね。閉じてしまいましょう。
