### ISSUE TITLE
Play2の最新版のチュートリアルも欲しいです。

### ISSUE THREAD

**Issue by applideveloper** [dwango/scala_text#60]
ドワンゴさん、お世話になっております。はてなの教科書でも勉強していたのですが、
https://github.com/hatena/Hatena-Textbook/blob/master/web-application-development-scala.md
Scalatraではなく、Play2の最新版で、Akka+Slickで非同期にMySQLを使った
CRUD+WebSocket+Ajaxも扱って欲しいです。
http://www.slideshare.net/yugolf/typesafe-reactiveplatformreactivesystem-scalasummitkansai

**Comment by xuwei-k** [comment]
こういうバグじゃない新規追加リクエストだとキリがないので

- 一言書いてissue閉じる
- なんかラベル決めてラベルつけて、こちらから積極的にやる可能性ほぼないけど、よいpull reqが来たらmergeするかもしれない、という態度を示す

のどちらかをするべきかな。

ひとまず、これだけ大雑把なリクエストされても、直近で対応できる可能性かなり低いです

**Comment by xuwei-k** [comment]
半分無責任に個人的意見としていうと、もし万が一そういうのやるとしても、社内的な流行(?)や、テキストに関わってる人のスキルとかにより、slickよりscalikejdbcになる可能性が高いと思います

**Comment by applideveloper** [comment]
すみません、Reactive Systemで、CRUDとかの基本が開設されている日本語の教科書があれば、Scalaが流行るんじゃないかと思ってリクエストしました。

**Comment by xuwei-k** [comment]
はい、もちろんそういうのがあったら嬉しい人が出てくることはわかりますけど、OSSで無償でやってるので、(なんか繰り返しになりますが)基本的に新規のリクエストだけされても対応できるかどうか何も責任持てないです。

あと、現状ある意味わざと外部ライブラリ使わない感じになってるので、外部ライブラリ増えれば増えるほどメンテナンスコスト上がる(個人的にはある程度メンテナンスしていきたい。Scala言語自体の非互換はライブラリに比べたらあまり急に出てこない)
みたいな観点があるので、(メンテナンスコストの観点からすると)とにかく流行ってるライブラリ色々使ったサンプル書くのは、いいことばかりでなくデメリットもある、などもありますね。


そのあたりはある意味多少暗黙の前提になってる、かつ個人的意見でもあるので、他の中の人の意見は色々違う可能性あるので、仮に新規の内容受け付けるにしても、
「どういう内容の新規追加のpull reqだったら受け入れる可能性高いか？」
は、こちらの責任で事前に書ける範囲で書いておいたほうがいいかも？
などもありますが

**Comment by applideveloper** [comment]
すみません、確かにそうですね、お金を払っているわけではないので
対応する責任は持たなくていいと思います。
Scala勉強会で、Playについて扱う予定がありますかと聞いたら、社内の情報が混じっているので、
取り除くのが面倒という理由で、公開されてないと聞きました。
要望があればissueに書くと採用されるかもしれないと聞いて書きました。
close権限がないのか、閉じれないので、閉じていただいて構いません。

**Comment by xuwei-k** [comment]
> 社内の情報が混じっている

は、ないかどうか完全には確認してないけど、それより

- 公開した部分より完成度低いとか
- ライブラリのアップデートが全部されてないとか
- 公開することになるとしても、全部一気ではなく順次公開にすればいいという判断になった、とか
- 結局、上に書いたようなメンテコストのトレードオフあるので、本当にplay部分も公開するべきか微妙

みたいな、他の様々な理由です。
あと、github慣れてない(?)のだと思いますけど、issue作成者が 
`close権限がないのか、閉じれない` は通常ありえないと思うので、ボタン見逃してるだけだと思います
(いずれにせよいったんこっちで閉じますね)

**Comment by applideveloper** [comment]
自分のgithubのisssueだと、横にcheckボックスにチェックして閉じれたのですが、チェックボックスがなくて、閉じれませんでした。xuwei-kさん、手数をおかけして、すみませんでした。

**Comment by applideveloper** [comment]
<img width="670" alt="2016-04-06 21 34 02" src="https://cloud.githubusercontent.com/assets/1066618/14316673/569c7a06-fc3f-11e5-985d-8805497715e5.png">

**Comment by xuwei-k** [comment]
それはたしかまとめてcloseかopenするとき用で、個々のissueのページの下の方にボタンあると思います
