### ISSUE TITLE
練習問題の解答を折りたたんで表示できないか？（in HTML版）

### ISSUE THREAD

**Issue by kmizu** [dwango/scala_text#63]
* HTMLでよく、「続きをよむ」クリックするまで表示が折りたたまれるのがありますが、あれをgitbookで実現できないかという話です（epub版は諦める）
* gitbookのmarkdown内で使えるHTMLタグには制限がある（＋折りたたみにはたぶんCSSをいじる必要がある？）ので、難しいかもしれませんがで、それができればスマートな気がします。
* 誰か詳しい人、情報plz

**Comment by kmizu** [comment]
sifueさんから情報提供があり、gitbookでも、cssとjavascriptを工夫すれば折りたたみ表示はできるとのこと（実際にそのようにしているとのこと）。というわけで、それを参考に折りたたみ表示化を進めることにする。

**Comment by kmizu** [comment]
ブロックレベルのタグの中ではmarkdown記法が無視されるらしく、tutが思い通りに解釈してくれないため、何らかのworkaroundが必要。

**Comment by kmizu** [comment]
ちょっと訂正。tutは単に行単位でtutとかが出てくるかだけで判断してるので、tutが処理する分には問題ない。gitbookがtutで処理されたmarkdownを読み込むときに、markdownとしての結果が無視されるのが問題。

**Comment by xuwei-k** [comment]
https://github.com/xuwei-k/scala_text/commit/5c417d7fd4b811f822016f16e



超あやうい実装なら動いたが、流石にこれは・・・




![next-next-sibling](https://cloud.githubusercontent.com/assets/389787/14422786/7ab81e40-0013-11e6-8a4b-f492641cf709.gif)

**Comment by kmizu** [comment]
凄いトリッキーですねw 

それはそうと、gitbookのpluginで

https://github.com/ymcatar/gitbook-plugin-sectionx

こういうのがあって、まさに目的に合致してそうなので、お試し中です。

**Comment by kmizu** [comment]
#64 で折りたたみは実現できるようになったので閉じる。
