### ISSUE TITLE
"implicitの値が解決される探索される範囲" という日本語微妙に変？

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#67]
- http://dwango.github.io/scala_text/implicit.html#implicitの値が解決される探索される範囲
- https://github.com/dwango/scala_text/blob/0fb95ccfcb44e2bc0d6c917a5130e00596e07efe/src/implicit.md#implicitの値が解決される探索される範囲

代案募集

**Comment by kmizu** [comment]
確かに日本語としてなんかおかしいですね…。何がいいだろう。

**Comment by matsu-chara** [comment]
"implicitパラメータの探索範囲" とかでしょうか？

**Comment by kmizu** [comment]
"implicit parameter"ではないもの、つまりimplicit conversionも扱いたいので、それだけだと微妙ですね。

"implicitの探索範囲" とか？（これは、implicit parameter/conversion両方を含めたいので曖昧な書き方にしたものです）

**Comment by xuwei-k** [comment]
> "implicitの探索範囲" とか？（これは、implicit parameter/conversion両方を含めたいので曖昧な書き方にしたものです）

自分は今のところ特に思いついてないので、他に無ければそれに +1 
(正確に書きたければ註入れるとかする？)
