### ISSUE TITLE
ページ遷移が遅い

### ISSUE THREAD

**Issue by matsu-chara** [dwango/scala_text#8]
見るのに支障がでるレベルで遅いので原因調査&対策が必要そうです・・。

**Comment by kmizu** [comment]
うむむ。こちらのクライアント環境では、そこまで遅くなかったですが…

**Comment by matsu-chara** [comment]
社内チャットコピペです

> （ざっと見た感じsearch_index.json が10MBぐらいあって、しかもブラウザキャッシュ効かないようにクエリパラメータ足してるっぽく、あやしい.....）

**Comment by xuwei-k** [comment]
https://github.com/dwango/scala_text/blob/gh-pages/search_index.json

これか。容量は確かに多い

**Comment by xuwei-k** [comment]
もし search_index が原因だとしたら、関連しそうな話題

https://github.com/GitbookIO/gitbook/issues/952

**Comment by xuwei-k** [comment]
search_index無効化するには、gitbookのversion上げないといけない？そもそもなぜ古いversion使ってるんだっけ・・・

**Comment by xuwei-k** [comment]
いや、別に古くない？

**Comment by matsu-chara** [comment]
gitbook-cliのデフォルト依存が若干古い(https://github.com/GitbookIO/gitbook-cli/blob/master/package.json)のですが

READMEによると
`gitbook versions:install 2.1.0` などして使ってくださいとのことのようです。
https://github.com/GitbookIO/gitbook-cli

**Comment by matsu-chara** [comment]
search_index.jsonの生成を無効にしても重さは改善しませんでした。
chrome以外のブラウザでは快適に見られるようなのでchromeの最近の変更で何か相性が悪くなった・・？などが考えられそうです。

**Comment by matsu-chara** [comment]
gitbookが生成するstyle.cssのうち
```
body{
text-rendering:optimizeLegibility;
font-smoothing:antialiased;
font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:14px;
letter-spacing:.2px;
text-size-adjust:100%
}
```
を消すとものすごい早くなるのでこの辺が原因のようです

**Comment by matsu-chara** [comment]
他の本もかなり遅いのでscala_text固有の問題では無さそうです。
https://www.gitbook.com/book/azu/javascript-plugin-architecture

**Comment by xuwei-k** [comment]
重い問題の直接的な原因じゃないとしても、毎回9MBのファイル登録するの微妙な気はするので、search_index.json 生成は無効にしていいんじゃないかなぁ

**Comment by xuwei-k** [comment]
search_index.json 削除してもやはり重いし、フォント関連なのかなぁ

**Comment by kmizu** [comment]
実際に読んでくださった読者の方からもやはりページ遷移が若干遅いとの話が…

https://twitter.com/gute_ist_tot/status/694527060530765824

**Comment by matsu-chara** [comment]
`sed -i 's/text-rendering:optimizeLegibility;//' style.css` したら爆速になりました

**Comment by matsu-chara** [comment]
メモ: #28 でcss取り除いたので若干汚くなっているのでchromeのバージョンが上がったら該当する処理を消したい

**Comment by nacika-ins** [comment]
`styles/website.css` を作成し、

```
body {
    text-rendering:auto;
    font-smoothing:none;
    font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:14px;
    letter-spacing:.2px;
    text-size-adjust:100%;
}
```

を加えたことで高速化しました。ありがとうございます。
