### ISSUE TITLE
Stackの実装例の解答がない

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#83]
http://dwango.github.io/scala_text/type-parameter.html

解答を移したり表示方法変えて整理したから間違って消えたのではなく、最初から無かったっぽい？

**Comment by kmizu** [comment]
去年のおぼろげな記憶では、その場で、自分が解答を提示してたような気がするので、たぶん最初からなかったのだと思います。まー、すぐ書けるので用意しますね…。

**Comment by matsu-chara** [comment]
https://dwango.slack.com/archives/rookies2015/p1432112591001545

**Comment by xuwei-k** [comment]
解答もそうだけど、問題自体を研修中に作ってた気はする。

というか、よく見ると他にも解答ないやつありそうだな(すごく単純で自明なものもあるが)

**Comment by kmizu** [comment]
去年はその辺、突貫工事で挑んだので研修の最中にどんどん追加されたりしてましたね。確か、mesoさんが練習問題ないから作ってー、と言ったので自分が作ったこともあった気が…。

**Comment by kmizu** [comment]
Fixed via #85
