### ISSUE TITLE
ScalaMockをMockitoに置き換える

### ISSUE THREAD

**Issue by pocketberserker** [dwango/scala_text#90]
理由は主に二点。

* ScalaMockはあまりメンテされていない印象を受ける
  * 現時点の最新コミット https://github.com/paulbutcher/ScalaMock/commit/cf8aa67cf163682cd52cbb4339e118da47703ae3
* 社内ではMockitoのほうが利用率が高い

**Comment by kmizu** [comment]
最後のコミットが1年前というのは確かに微妙な印象を受けますね。賛成します。
