### ISSUE TITLE
higher kindについて書く？

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#99]
https://github.com/dwango/scala_text/pull/98 <del>で使用しているので、もしそれがmergeされるなら。</del>mergeされた

- 注で1行2行でなにかへのリンク貼って済ませるのか？
- わりとガッツリ書くのか？

あたりをまず決める？

**Comment by matsu-chara** [comment]
入門的な範囲を超えないようにという意味合いで 1,2行の方針に +1 です。

**Comment by kmizu** [comment]
・注で1〜2行程度というのはよいのですが、higher kinded genericsに関するまとまった資料って、書籍であれWeb上の資料であれ、ほとんどないですよね。
・Scalaだったら、 https://adriaanm.github.io/files/higher.pdf 読めとか？

**Comment by xuwei-k** [comment]
言われてみると、なにかわかりやすいやつあったっけ・・・。コップ本にはどう書いてあったかなぁ・・・(全く覚えてない)

FP in Scalaでも使ってるのだから、記述は最低限あるはずか？

**Comment by kmizu** [comment]
FP in Scala日本語版より引用：

> 前章のParser 型と同様に、型コンストラクタF が抽象化されています。これはF[_] として記
> 述されていますが、アンダースコア（_）は、F が型ではなく、1 つの型引数を受け取る型
> コンストラクタであることを示しています。他の関数を引数として受け取る関数のことを
> 「高階関数」と呼ぶのと同じように、Foldable のようなものを高階型コンストラクタまたは
> 高類型と呼びます※8。

本当に最低限ですが説明はありますね

**Comment by kmizu** [comment]
型システム入門のTocより

・第Ⅵ部「高階の型システム」
　・第29章「型演算子とカインド」
　・第30章「高階多相」
　・第31章「高階部分型付け」
　・第32章「事例：純粋関数的オブジェクト」

これなら、TAPL読めでいい気がしてきました（サブタイピングもちゃんと扱っているし）

**Comment by xuwei-k** [comment]
> これなら、TAPL読めでいい気がしてきました

そうですね、他になにか代案でてこなそうなら、ひとまずそれに +1

**Comment by y-yu** [comment]
TAPLは大変よい本であると僕も思いますが、29章〜31章を読むには、ぱっと見た感じおそらく、

- 単純型付きラムダ計算（II部）
- 多相性（22章）
- 全称型（23章）

あたりを知っていなければならないような気がしていて、これは結構重いので、我々で説明を用意するのもよいと思いました。
（もちろん、これは今後の課題になりそうですが……）

**Comment by kmizu** [comment]
よりわかりやすい説明を（今後）我々で提供できると良い、にはもちろん賛成です。ただ、29章最初の方を読むと、「直観」的な説明が最初にかかれていて、それまでの内容あまり覚えてなくても概要はわかるようになっていました。

**Comment by y-yu** [comment]
なるほど。でしたらひとまずは👍です。
